---
title: "AnáliseP5"
author: "Gabriel Leonardo Fadul"
date: "2023-11-05"
output: html_document
---
#Análise Parcial 5

#baixando e pegando os pacotes e banco de dados
```{r}
vendas<- read.csv("vendas.csv")
devolucao <- read.csv("devolução_atualizado.csv")
library(tidyverse)
library(conflicted)
conflict_prefer("filter", "dplyr")
```

#tema estat
```{r}
cores_estat <- c("#A11D21", "#003366", "#CC9900", "#663333", "#FF6600", "#CC9966", "#999966", "#006606", "#008091", "#041835", "#666666")
theme_estat <- function(...) {
    theme <- ggplot2::theme_bw() +
        ggplot2::theme(
            axis.title.y = ggplot2::element_text(colour = "black", size = 12),
            axis.title.x = ggplot2::element_text(colour = "black", size = 12),
            axis.text = ggplot2::element_text(colour = "black", size = 9.5),
            panel.border = ggplot2::element_blank(),
            axis.line = ggplot2::element_line(colour = "black"),
            legend.position = "top",
            ...
        )

    return(
        list(
            theme,
            scale_fill_manual(values = cores_estat),
            scale_colour_manual(values = cores_estat)
        )
    )
}
```

#tirando os itens repetidos das vendas
```{r}
vendas<- vendas %>%
  distinct(Unique.ID, .keep_all = TRUE)
```

#juntando os bancos
```{r}
x <- vendas%>%
  select(Brand, Unique.ID)
motivos <- left_join(x, devolucao, by = "Unique.ID")
motivos <- motivos%>%
  filter(!is.na(Motivo.devolução))
```

#tabela simples
```{r}
tabela <- table(motivos$Brand, motivos$Motivo.devolução)
tabela
```

#agrupando por marca
```{r}
marcas <- motivos%>%
  filter(!is.na(Brand))%>%
  group_by(Brand, Motivo.devolução)%>%
  summarise(Freq = n())
```

#grafico pizza para cada marca
```{r}
marcas <- motivos%>%
  filter(!is.na(Brand))%>%
  group_by(Brand, Motivo.devolução)%>%
  summarise(Freq = n())%>%
  mutate(Prop = round(100*(Freq/sum(Freq)), 2)) %>%
  arrange(desc(Motivo.devolução)) %>%
  mutate(posicao = cumsum(Prop) - 0.5*Prop)

ggplot(marcas) +
  aes(x = factor(""), y = Prop , fill = factor(Motivo.devolução)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") + facet_wrap(Brand ~.) +
  geom_text(aes(x = 1.8, y = posicao, label = paste0(Prop, "%")), color = "black", size = 2.1) +
  theme_void() +
  theme(legend.position = "top") +
  scale_fill_manual(values = cores_estat, name = 'Motivo das devoluções') 
ggsave("grfc_AP5.png", width = 158, height = 93, units = "mm")
```

